
services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - /srv/enabion/prod/env/db.env
    volumes:
      - /srv/enabion/_volumes/prod/postgres:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build:
      context: ../apps/backend
    restart: unless-stopped
    env_file:
      - /srv/enabion/prod/env/backend.env
    depends_on:
      - db
    networks:
      - internal
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=enabion_edge"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.backend.rule=Host(`api.dev.enabion.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.routers.backend.service=backend-svc"
      - "traefik.http.services.backend-svc.loadbalancer.server.port=4000"
      - "traefik.http.routers.backend-web.rule=Host(`api.dev.enabion.com`)"
      - "traefik.http.routers.backend-web.entrypoints=web"
      - "traefik.http.routers.backend-web.middlewares=redirect-to-https"
      - "traefik.http.routers.backend-web.service=backend-svc"

  frontend:
    build:
      context: ../apps/frontend
    restart: unless-stopped
    env_file:
      - /srv/enabion/prod/env/frontend.env
    depends_on:
      - backend
    networks:
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=enabion_edge"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.frontend.rule=Host(`dev.enabion.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.routers.frontend.service=frontend-svc"
      - "traefik.http.services.frontend-svc.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend-web.rule=Host(`dev.enabion.com`)"
      - "traefik.http.routers.frontend-web.entrypoints=web"
      - "traefik.http.routers.frontend-web.middlewares=redirect-to-https"
      - "traefik.http.routers.frontend-web.service=frontend-svc"

networks:
  internal:
  edge:
    external: true
    name: enabion_edge
