
services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - /srv/enabion/prod/env/db.env
    volumes:
      - /srv/enabion/_volumes/prod/postgres:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build:
      context: ../apps/backend
    restart: unless-stopped
    env_file:
      - /srv/enabion/prod/env/backend.env
    depends_on:
      - db
    networks:
      - internal
      - edge

  frontend:
    build:
      context: ../apps/frontend
    restart: unless-stopped
    env_file:
      - /srv/enabion/prod/env/frontend.env
    depends_on:
      - backend
    networks:
      - edge

networks:
  internal:
  edge:
    external: true
    name: enabion_edge
